# -*- coding: utf-8 -*-
"""yolov11_fruit_freshness_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trz-LehQj6eme9TyIpY9qxmFVsUuH378

    By William Flores, Lathrell Pagsuguiron, and Jhervince Rada
"""

from roboflow import Roboflow
from ultralytics import YOLO
import os
!nvidia-smi


HOME = os.getcwd()

print(HOME)

!pip install ultralytics roboflow


model = YOLO("yolo11n.pt")


rf = Roboflow(api_key="BV0zrsFIdMW4Ey8KWIwi")
project = rf.workspace(
    "deep-learning-computer-vision-project").project("rotten-fruit-detector")
version = project.version(3)
dataset = version.download("yolov11")

epochs = 100
batch = 16
patience = 5
dataset_dir = f'{dataset.location}/data.yaml'
imgsz = 640

model = YOLO("yolo11n.pt")

results = model.train(
    data=dataset_dir,
    epochs=epochs,
    batch=batch,
    patience=patience,
    imgsz=imgsz,
    name="new"
)

accuracy_results = model.val()
